### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by jwodder** [dandi/zarr_checksum#40]
Please create a Git tag whenever a new release is made (and create tags for past releases as well).  This will make it easier for someone looking at the Git history to tell what was released in which version.

**Comment by jjnesbitt** [comment]
> Pretty please @jjnesbitt or let us know if you need help to address this -- hard to see what is even released or not by looking at git history.

I'm on vacation at the moment. If you'd like to make a pull request please feel free.

**Comment by yarikoptic** [comment]
@jjnesbitt I ran into this oddity of having no release tags again, spent some time trying to figure it out locally since "how could it be?" only to come to this issue.

@jjnesbitt could you please provide release tags and ideally also mint releases (at least for the latest tag) on github ?

**Comment by jjnesbitt** [comment]
This has been completed.
