### ISSUE TITLE
Add to conda-forge

### ISSUE THREAD

**Issue by jwodder** [dandi/zarr_checksum#6]
In order for this to be usable as a dependency of dandi-cli, it needs to be added to conda-forge, which can be done by creating a pull request against https://github.com/conda-forge/staged-recipes.

**Comment by AlmightyYakob** [comment]
Why does dandi-cli require this dependency to be available on conda forge?

**Comment by jwodder** [comment]
@AlmightyYakob Because we distribute dandi-cli on conda-forge, and that means that all of its dependencies must be available via conda as well.

**Comment by jwodder** [comment]
Done by @AlmightyYakob: https://github.com/conda-forge/zarr-checksum-feedstock
